http://localhost/svsignal/api/v1/group/get/beacon

###

http://localhost/svsignal/api/v1/group/all

###

http://localhost/svsignal/api/v1/group/beacon/signals/all

###

http://localhost/svsignal/api/v1/signal/get/beacon.1234.rx

###

#/svsignal/api/v1/signal/data/{SignalKey}/{Begin}/{End}
http://localhost/svsignal/api/v1/signal/getdata/beacon.1234.rx/1699018580/1699118580


###

http://localhost/svsignal/api/v1/signal/getdata?signalkey=blzone.1794_err_sbrf&begin=1699038000&end=1699124400
