server_path_cfg: /usr/insiteexpert/etc/server.yaml

svsignal:
  debug_level: 0
  
  rabbitmq:
    url: amqp://rabbit:rabbitie@rabbitmq:5672/?heartbeat=10
    queue_name: "svsignal"
    qos: 100

  http:
    # address: :5501
    unixsocket: /usr/insiteexpert_v4/sock/svsignal.sock
    user: root
    password: 234123412

  TypeDataBase: sqlite

#  mysql:
#    host: mysql
#    user: apache2
#    password: apache2data
#    port: 3306
#    database: insiteexpert_v4

  sqlite:
    file: "/usr/svsignal/database/svsignal.db"
    pragma:
      - "PRAGMA journal_mode = WAL"
      - "PRAGMA synchronous = OFF"

  bulk_size: 1000
  buffer_size: 10000
  period_save: 60
