config:
  debug_level: 4
  
  rabbitmq:
    url: amqp://rabbit:rabbitie@rabbitmq:5672/?heartbeat=10
    queue_name: "svsignal"
    qos: 100

  mysql:
    host: mysql
    user: apache2
    password: apache2data
    port: 3306
    database: insiteexpert_v4

  http:
    # address: :5501
    unixsocket: /usr/insiteexpert_v4/sock/svsignal.sock
    user: root
    password: 234123412
