server_path_cfg: /usr/insiteexpert/etc/server.yaml

svsignal:
  pprof:
    enable: false
    block: true
    mutex: true
    http_addr: :6060

  debug_level: 0
  
  grpc-server:        
    address: :8818    # адрес, порт grpc сервера на котором будет работать сервис
  
  rabbitmq:
    url: amqp://rabbit:rabbitie@192.168.67.3:5672/?heartbeat=10
    queue_name: "svsignal1"
    qos: 100

#  http:
#    # address: :5501
#    unixsocket: /usr/insiteexpert_v4/sock/svsignal.sock
#    user: root
#    password: 234123412

  TypeDataBase: sqlite

#  mysql:
#    host: mysql
#    user: svs
#    password: svs
#    port: 3306
#    database: svsignal

  sqlite:
    # file: "/usr/svsignal/database/svsignal.db"
    file: "/datadisk/svsignal_db/svsignal.db"
    pragma:
      - "PRAGMA journal_mode = WAL"
      - "PRAGMA synchronous = OFF"

  bulk_size: 1000
  buffer_size: 10000
  period_save: 60

svsignal_http_gateway:
  debug_level: 0
  grpc_address: :8818
#  proxy_http_addr: :8002
  proxy_unixsocket: /usr/insiteexpert_v4/sock/svsignal.sock
